### ISSUE TITLE
writeValue writes out header in each call.

### ISSUE THREAD

**Issue by flappingeagle** [FasterXML/jackson-dataformat-csv#71] opened 2015-03-19 10:00 UTC
Is it correct and ok that the following code ....

```java
        ByteArrayOutputStream bos = new ByteArrayOutputStream();

        Builder builder = CsvSchema.builder();
        builder.addColumn("col1");
        builder.addColumn("col2");

        CsvSchema csvSchema = builder.build().withHeader();

        CsvMapper csvMapper = new CsvMapper();
        ObjectWriter csvWriter = csvMapper.writer(csvSchema);

        List<String> line1 = new ArrayList<>();
        line1.add("line1-val1");
        line1.add("line1-val2");
        
        csvWriter.writeValue(bos, line1);
        
        List<String> line2 = new ArrayList<>();
        line2.add("line2-val1");
        line2.add("line2-val2");
        
        csvWriter.writeValue(bos, line2);

        System.out.println(bos.toString());

```

would produce the following output:

```java
col1,col2
line1-val1,line1-val2
col1,col2
line2-val1,line2-val2
```

I would have expected that the header is only written out once and i can use "writeValue" to write a single line. It is much better to write out single lines because that way i do not have to keep a really large List in the java heap until i finally write it out.

With the following Hack i can make Jackson act like i would expect it ;-) So it would be ok for me either way.

```java
        ...
        csvWriter.writeValue(bos, line1);
        
        // construct writer again, without header-writing-feature for other lines...
        csvSchema = csvSchema.withoutHeader();
        csvWriter = csvMapper.writer(csvSchema);
        ...
        csvWriter.writeValue(bos, line2);
        ...
```

**Comment by cowtowncoder** [comment] 2015-03-19 17:02
Hmmh. I will have to think about this. The problem is that each `writeValue()` is -- from Jackson perspective -- a separate "document". So in that sense it may be as designed. But obviously it's not intuitive or sensible from user perspective.
I'll have to see if this could be improved so that `CsvGenerator` would be aware of header being written.
Actually it could just be a bug, so I'll have a look when I get a chance.

One way to work around this would be to separately construct `CsvGenerator`, and using `CsvGenerator.writeValueAs()`, but its interaction with header production might be problematic.

But I think what you may really want to use is the new method(s) added in 2.5: `ObjectWriter.writeValues()` (http://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/ObjectWriter.html#writeValues%28java.io.OutputStream%29).
It returns a `SequenceWriter` which has `write` and `writeAll` methods to use.
That should properly handle headers; and if not, that would definitely be a bug.

I will keep this issue open to hopefully have a look if regular `writeValue()` usage could be improved wrt header output. I don't see any upside to duplicate header writes.

**Comment by flappingeagle** [comment] 2015-03-20 08:42
yes thanks. I tested the new method ```ObjectWriter.writeValues()``` and it works correctly, so that the given sequence-writer only writes the header once in the first write-call, like you said.

**Comment by cowtowncoder** [comment] 2015-03-20 18:31
Ok good. There are other reasons why `writeValues()` is a good addition (there is less overhead since serialization context is not closed etc), so it makes sense to use. I will still dig into existing method as I've said.

**Comment by cowtowncoder** [comment] 2015-03-26 20:49
Looking at test case again, I realize that usage as is may be something CSV module can not support.
Problem is that instead of constructing and reusing `CsvGenerator` (which has state, and may be aware of output of header), use of `OutputStream`, `Writer`, or other physical output object means there is no state available. So each write starts from scratch and has no way of knowing if header line has been written. `CsvWriter` is the only place that theoretically could have state, but it is actually immutable so it also can not have per-call state as that would prevent its concurrent use.

It should however be possible to construct `CsvGenerator` (sub-type of `JsonGenerator`) and avoid headers. I'll see if I can add a test to verify this is the case.

In the end use of `ObjectWriter.writeValues()` is the recommended method, and the proper resolution.

**Comment by cowtowncoder** [comment] 2015-03-26 21:15
Verified that multiple writes with same `CsvGenerator` do NOT produce multiple headers, closing.

**Closed by cowtowncoder** 2015-03-26 21:15 UTC
